name: Security Scan

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
  workflow_dispatch:


jobs:
  security-scan:
    runs-on: [self-hosted, Windows, X64]  # Targets your self-hosted runner pool
    defaults:
      run:
        shell: powershell -ExecutionPolicy Bypass {0}
    permissions:
      contents: read
      security-events: write  # Crucial for uploading SARIF files
      actions: read           # Required for baseline path lookups

    steps:
      # Clone only the specific path from that branch (Sparse Checkout)
      - name: Checkout specific path
        uses: actions/checkout@v4
        with:
          ref: 'main'
          sparse-checkout: |
            backend
          sparse-checkout-cone-mode: true
      - name: Run OpenGrep Scan and Output SARIF
        working-directory: .\backend
        run: |
          conda activate semgrep 
          $env:PYTHONUTF8=1
          opengrep scan --config auto --sarif --output=semgrep.sarif

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Ensures results upload even if flaws are found
        with:
          sarif_file: .\backend\semgrep.sarif